### ISSUE TITLE
cannot create activity.

### ISSUE THREAD

**Issue by superkevin5** [airmnb/airmnb-weapp#13]
![image](https://user-images.githubusercontent.com/8369050/42816551-907d6c44-8a0e-11e8-8111-2b4c4263db69.png)

**Comment by superopengl** [comment]
@superkevin5 I cannot reproduce this issue on my local. I used Chinese language as your screenshot shows. I guess this might be due to the App running on Windows? Is your Windows of Chinese culture?

**Comment by superkevin5** [comment]
works in mobile, but not in my simulator. close it for now
